"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import NavBar from "@/components/NavBar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const navigati = useNavigation();
  const isLoginPage = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NextUIProvider> */}
        {/* <NextThemesProvider attribute="class" defaultTheme="dark"> */}
        {isLoginPage === "/" ? null : <NavBar />}
        {children}
        {/* </NextThemesProvider> */}
        {/* </NextUIProvider> */}
      </body>
    </html>
  );
}
